call as function
otherwise generates an error - "AttributeError: 'function' object has no attribute 'named_parameters'" 

hence call model as a function